# Generated by Django 6.0.8 on 2026-09-11 10:08

import apps.resumes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A label you recognise, e.g. 'Backend - 2026'.", max_length=150)),
                ('file', models.FileField(upload_to=apps.resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'rtf', 'txt'])])),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, help_text='Which roles this version is tuned for.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes_resume',
                'ordering': ['-is_default', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_resume_per_user'), models.UniqueConstraint(fields=('user', 'name'), name='unique_resume_name_per_user')],
            },
        ),
    ]
