# Generated by Django 6.0.8 on 2026-09-11 10:08

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('current_title', models.CharField(blank=True, max_length=160)),
                ('current_company', models.CharField(blank=True, max_length=160)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, help_text='Total years of professional experience.', max_digits=4)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills.')),
                ('summary', models.TextField(blank=True)),
                ('desired_roles', models.TextField(blank=True, help_text='Comma-separated target job titles.')),
                ('desired_locations', models.TextField(blank=True, help_text='Comma-separated target locations.')),
                ('open_to_remote', models.BooleanField(default=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('expected_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=8)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('work_authorization', models.CharField(choices=[('citizen', 'Citizen'), ('permanent_resident', 'Permanent resident'), ('work_visa', 'Work visa'), ('student_visa', 'Student visa'), ('needs_sponsorship', 'Needs sponsorship'), ('other', 'Other')], default='citizen', max_length=32)),
                ('requires_sponsorship', models.BooleanField(default=False)),
                ('custom_answers', models.JSONField(blank=True, default=dict, help_text='Extra question -> answer pairs the form filler can reuse.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_profile',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reminders', models.BooleanField(default=True)),
                ('reminder_lead_days', models.PositiveIntegerField(default=1, help_text="Days before the due date a reminder becomes 'upcoming'.")),
                ('default_follow_up_days', models.PositiveIntegerField(default=7, help_text='Auto-schedule a follow-up this many days after applying.')),
                ('auto_create_follow_ups', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=16)),
                ('allow_auto_submit', models.BooleanField(default=False, help_text='Only applies to sources with an official application API.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user settings',
                'db_table': 'accounts_settings',
            },
        ),
    ]
