# Generated by Django 6.0.8 on 2026-09-11 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('job_url', models.URLField(blank=True, max_length=500)),
                ('salary', models.CharField(blank=True, help_text="Free text, e.g. '18-24 LPA' or '$120k'.", max_length=120)),
                ('experience_required', models.CharField(blank=True, help_text="Free text, e.g. '3-5 years'.", max_length=120)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills.')),
                ('job_description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('naukri', 'Naukri'), ('glassdoor', 'Glassdoor'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('company_site', 'Company site'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='saved', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('saved', 'Saved'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'job status history',
                'db_table': 'jobs_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'status'], name='jobs_job_user_id_ec4047_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='jobs_job_user_id_58dc09_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('job_url', ''), _negated=True), fields=('user', 'job_url'), name='unique_job_url_per_user'),
        ),
    ]
