# Generated by Django 6.0.8 on 2026-09-11 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name_snapshot', models.CharField(blank=True, help_text='Resume label at submission time, so history survives deletion.', max_length=150)),
                ('method', models.CharField(choices=[('manual', 'Filled manually'), ('assisted', 'Automation-assisted (user submitted)'), ('api', 'Official API submission')], default='manual', max_length=16)),
                ('outcome', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared — awaiting your submit'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='draft', max_length=16)),
                ('cover_letter', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Screening question -> answer pairs used for this application.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, help_text='Which resume was sent. Kept if the resume is later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='application_user_id_aaf56b_idx'), models.Index(fields=['user', 'outcome'], name='application_user_id_5f1f16_idx')],
            },
        ),
    ]
