# Generated by Django 6.0.8 on 2026-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='method',
            field=models.CharField(choices=[('manual', 'Filled manually'), ('assisted', 'Automation-assisted'), ('api', 'Official API')], default='manual', max_length=16),
        ),
    ]
