# Generated by Django 6.0.8 on 2026-09-11 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(help_text="Hostname, e.g. 'boards.greenhouse.io'.", max_length=180, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Allow assisted form filling on this host.')),
                ('supports_official_api', models.BooleanField(default=False, help_text='Vendor publishes a documented application API. Required for auto-submit.')),
                ('api_docs_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Terms-of-service notes, quirks, selector overrides.')),
                ('selector_overrides', models.JSONField(blank=True, default=dict, help_text='canonical_field -> CSS selector, for sites the generic heuristics miss.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'automation_supported_site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_review', 'Filled - awaiting your review and submit'), ('submitted', 'Submitted via official API'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unsupported', 'Site not supported')], db_index=True, default='queued', max_length=20)),
                ('fields_filled', models.JSONField(blank=True, default=dict, help_text='canonical_field -> value that was typed.')),
                ('fields_skipped', models.JSONField(blank=True, default=list, help_text='Fields found but left for the user.')),
                ('unanswered_questions', models.JSONField(blank=True, default=list, help_text='Questions with no saved answer. Surfaced so the user can add them.')),
                ('resume_uploaded', models.BooleanField(default=False)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='automation/screenshots/')),
                ('submit_attempted', models.BooleanField(default=False)),
                ('stop_reason', models.CharField(blank=True, help_text='Why the run halted before submitting, in plain language.', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_run', to='applications.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='automation.supportedsite')),
            ],
            options={
                'db_table': 'automation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationrun')),
            ],
            options={
                'db_table': 'automation_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['user', '-created_at'], name='automation__user_id_61b03a_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['status'], name='automation__status_fffb3e_idx'),
        ),
    ]
